version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ilia
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  punch-timesheet-api:
    container_name: punch-timesheet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .docker.env

volumes:
  postgres-data:
